quarkus.application.name=volunteer-hours-service

%dev.quarkus.datasource.devservices.enabled=false
%test.quarkus.datasource.devservices.enabled=false

%dev.quarkus.hibernate-orm.enabled=false
%test.quarkus.hibernate-orm.enabled=false

%dev.quarkus.liquibase.enabled=false
%test.quarkus.liquibase.enabled=false