apiVersion: v1
kind: Secret
metadata:
  name: {{ include "volunteer-hours-service.fullname" . }}-db
type: Opaque
stringData:
  QUARKUS_DATASOURCE_USERNAME: {{ .Values.database.username | quote }}
  QUARKUS_DATASOURCE_PASSWORD: {{ .Values.database.password | quote }}
  QUARKUS_DATASOURCE_JDBC_URL: {{ .Values.database.jdbcUrl | quote }}